export const GET_CITY_WEATHER = 'GET_CITY_WEATHER'
export const GET_CITY_WEATHER_SUCCESS = 'GET_CITY_WEATHER_SUCCESS'
export const GET_CITY_WEATHER_FAILURE = 'GET_CITY_WEATHER_FAILURE'
export const GET_CITY_WEATHER_INIT = 'GET_CITY_WEATHER_INIT'